// Code generated by pigeon; DO NOT EDIT.

package grammar

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

type Type string

const (
	TypeFunc = Type("func")
)

// AstNode is an interface
type AstNode interface {
	Children() []AstNode
}

type Func struct {
	IsConst bool
	Params  []string
	Name    string
	Body    string
}

func (fn *Func) Type() Type {
	return TypeFunc
}

func (fn *Func) Eval() []float64 {
	return nil
}

type PowerExpr struct {
	Base  Scalar
	Power Scalar
}

func (exp PowerExpr) Children() []AstNode {
	return []AstNode{exp.Base, exp.Power}
}

func (exp PowerExpr) Val() float64 {
	return math.Pow(exp.Base.Val(), exp.Power.Val())
}

type MultExpr struct {
	Left  Scalar
	Right Scalar
}

func (exp MultExpr) Children() []AstNode {
	return []AstNode{exp.Left, exp.Right}
}

func (exp MultExpr) Val() float64 {
	return exp.Left.Val() * exp.Right.Val()
}

type DivExpr struct {
	Left  Scalar
	Right Scalar
}

func (exp DivExpr) Children() []AstNode {
	return []AstNode{exp.Left, exp.Right}
}

func (exp DivExpr) Val() float64 {
	return exp.Left.Val() / exp.Right.Val()
}

type AddExpr struct {
	Left  Scalar
	Right Scalar
}

func (exp AddExpr) Children() []AstNode {
	return []AstNode{exp.Left, exp.Right}
}

func (exp AddExpr) Val() float64 {
	return exp.Left.Val() + exp.Right.Val()
}

type SubExpr struct {
	Left  Scalar
	Right Scalar
}

func (exp SubExpr) Children() []AstNode {
	return []AstNode{exp.Left, exp.Right}
}

func (exp SubExpr) Val() float64 {
	return exp.Left.Val() - exp.Right.Val()
}

type Scalar interface {
	AstNode
	Val() float64
}

type ScalarLit struct {
	val float64
}

func (exp ScalarLit) Children() []AstNode {
	return []AstNode{}
}

func (s ScalarLit) Val() float64 {
	return s.val
}

type ScalarVar struct {
	name string
	val  *float64
}

func (exp ScalarVar) Children() []AstNode {
	return []AstNode{}
}

func (s ScalarVar) Val() float64 {
	return *s.val
}

func (s *ScalarVar) Set(f float64) {
	s.val = &f
}

func (s *ScalarVar) SetLoc(f *float64) {
	s.val = f
}

var g = &grammar{
	rules: []*rule{
		{
			name: "ScalarExpr",
			pos:  position{line: 136, col: 1, offset: 2019},
			expr: &actionExpr{
				pos: position{line: 136, col: 14, offset: 2032},
				run: (*parser).callonScalarExpr1,
				expr: &seqExpr{
					pos: position{line: 136, col: 14, offset: 2032},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 136, col: 14, offset: 2032},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 136, col: 20, offset: 2038},
								name: "ScalarFactor",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 136, col: 33, offset: 2051},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 136, col: 35, offset: 2053},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 136, col: 40, offset: 2058},
								expr: &ruleRefExpr{
									pos:  position{line: 136, col: 40, offset: 2058},
									name: "AddExpr",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AddExpr",
			pos:  position{line: 167, col: 1, offset: 2699},
			expr: &actionExpr{
				pos: position{line: 167, col: 11, offset: 2709},
				run: (*parser).callonAddExpr1,
				expr: &seqExpr{
					pos: position{line: 167, col: 11, offset: 2709},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 167, col: 11, offset: 2709},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 167, col: 15, offset: 2713},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 167, col: 15, offset: 2713},
										val:        "+",
										ignoreCase: false,
									},
									&litMatcher{
										pos:        position{line: 167, col: 21, offset: 2719},
										val:        "-",
										ignoreCase: false,
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 167, col: 26, offset: 2724},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 167, col: 28, offset: 2726},
							label: "arg",
							expr: &ruleRefExpr{
								pos:  position{line: 167, col: 32, offset: 2730},
								name: "ScalarFactor",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 167, col: 45, offset: 2743},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "ScalarFactor",
			pos:  position{line: 179, col: 1, offset: 2900},
			expr: &actionExpr{
				pos: position{line: 179, col: 16, offset: 2915},
				run: (*parser).callonScalarFactor1,
				expr: &seqExpr{
					pos: position{line: 179, col: 16, offset: 2915},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 179, col: 16, offset: 2915},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 179, col: 22, offset: 2921},
								name: "Power",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 179, col: 28, offset: 2927},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 179, col: 30, offset: 2929},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 179, col: 35, offset: 2934},
								expr: &ruleRefExpr{
									pos:  position{line: 179, col: 35, offset: 2934},
									name: "MultExpr",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MultExpr",
			pos:  position{line: 211, col: 1, offset: 3627},
			expr: &actionExpr{
				pos: position{line: 211, col: 12, offset: 3638},
				run: (*parser).callonMultExpr1,
				expr: &seqExpr{
					pos: position{line: 211, col: 12, offset: 3638},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 211, col: 12, offset: 3638},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 211, col: 16, offset: 3642},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 211, col: 16, offset: 3642},
										val:        "*",
										ignoreCase: false,
									},
									&litMatcher{
										pos:        position{line: 211, col: 22, offset: 3648},
										val:        "/",
										ignoreCase: false,
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 211, col: 27, offset: 3653},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 211, col: 29, offset: 3655},
							label: "arg",
							expr: &ruleRefExpr{
								pos:  position{line: 211, col: 33, offset: 3659},
								name: "Power",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 211, col: 39, offset: 3665},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Power",
			pos:  position{line: 223, col: 1, offset: 3823},
			expr: &actionExpr{
				pos: position{line: 223, col: 9, offset: 3831},
				run: (*parser).callonPower1,
				expr: &seqExpr{
					pos: position{line: 223, col: 9, offset: 3831},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 223, col: 9, offset: 3831},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 223, col: 15, offset: 3837},
								name: "Scalar",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 223, col: 22, offset: 3844},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 223, col: 24, offset: 3846},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 223, col: 29, offset: 3851},
								expr: &ruleRefExpr{
									pos:  position{line: 223, col: 29, offset: 3851},
									name: "PowerExpr",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PowerExpr",
			pos:  position{line: 247, col: 1, offset: 4236},
			expr: &actionExpr{
				pos: position{line: 247, col: 13, offset: 4248},
				run: (*parser).callonPowerExpr1,
				expr: &seqExpr{
					pos: position{line: 247, col: 13, offset: 4248},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 247, col: 13, offset: 4248},
							val:        "^",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 247, col: 17, offset: 4252},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 247, col: 19, offset: 4254},
							label: "power",
							expr: &ruleRefExpr{
								pos:  position{line: 247, col: 25, offset: 4260},
								name: "Scalar",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 247, col: 32, offset: 4267},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Scalar",
			pos:  position{line: 251, col: 1, offset: 4293},
			expr: &choiceExpr{
				pos: position{line: 251, col: 10, offset: 4302},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 251, col: 10, offset: 4302},
						run: (*parser).callonScalar2,
						expr: &seqExpr{
							pos: position{line: 251, col: 10, offset: 4302},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 251, col: 10, offset: 4302},
									val:        "(",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 251, col: 14, offset: 4306},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 251, col: 16, offset: 4308},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 251, col: 21, offset: 4313},
										name: "ScalarExpr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 251, col: 32, offset: 4324},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 251, col: 34, offset: 4326},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 253, col: 5, offset: 4354},
						run: (*parser).callonScalar10,
						expr: &labeledExpr{
							pos:   position{line: 253, col: 5, offset: 4354},
							label: "ident",
							expr: &ruleRefExpr{
								pos:  position{line: 253, col: 11, offset: 4360},
								name: "Ident",
							},
						},
					},
					&actionExpr{
						pos: position{line: 256, col: 5, offset: 4462},
						run: (*parser).callonScalar13,
						expr: &labeledExpr{
							pos:   position{line: 256, col: 5, offset: 4462},
							label: "num",
							expr: &ruleRefExpr{
								pos:  position{line: 256, col: 9, offset: 4466},
								name: "Number",
							},
						},
					},
					&actionExpr{
						pos: position{line: 259, col: 5, offset: 4567},
						run: (*parser).callonScalar16,
						expr: &seqExpr{
							pos: position{line: 259, col: 5, offset: 4567},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 259, col: 5, offset: 4567},
									val:        "-",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 259, col: 9, offset: 4571},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 259, col: 11, offset: 4573},
									label: "scalar",
									expr: &ruleRefExpr{
										pos:  position{line: 259, col: 18, offset: 4580},
										name: "Scalar",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 266, col: 1, offset: 4675},
			expr: &actionExpr{
				pos: position{line: 266, col: 10, offset: 4684},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 266, col: 10, offset: 4684},
					exprs: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 266, col: 10, offset: 4684},
							expr: &charClassMatcher{
								pos:        position{line: 266, col: 10, offset: 4684},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 266, col: 17, offset: 4691},
							expr: &seqExpr{
								pos: position{line: 266, col: 19, offset: 4693},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 266, col: 19, offset: 4693},
										val:        ".",
										ignoreCase: false,
									},
									&zeroOrMoreExpr{
										pos: position{line: 266, col: 23, offset: 4697},
										expr: &charClassMatcher{
											pos:        position{line: 266, col: 23, offset: 4697},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Assign",
			pos:  position{line: 271, col: 1, offset: 4799},
			expr: &actionExpr{
				pos: position{line: 271, col: 10, offset: 4808},
				run: (*parser).callonAssign1,
				expr: &seqExpr{
					pos: position{line: 271, col: 10, offset: 4808},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 271, col: 10, offset: 4808},
							label: "prefix",
							expr: &choiceExpr{
								pos: position{line: 271, col: 18, offset: 4816},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 271, col: 18, offset: 4816},
										val:        "def",
										ignoreCase: false,
									},
									&litMatcher{
										pos:        position{line: 271, col: 26, offset: 4824},
										val:        "let",
										ignoreCase: false,
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 271, col: 33, offset: 4831},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 271, col: 35, offset: 4833},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 271, col: 40, offset: 4838},
								name: "Ident",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 271, col: 46, offset: 4844},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 271, col: 48, offset: 4846},
							label: "params",
							expr: &ruleRefExpr{
								pos:  position{line: 271, col: 55, offset: 4853},
								name: "Params",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 271, col: 62, offset: 4860},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 271, col: 64, offset: 4862},
							val:        "=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 271, col: 68, offset: 4866},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 271, col: 70, offset: 4868},
							name: "Expr",
						},
					},
				},
			},
		},
		{
			name: "Vector",
			pos:  position{line: 285, col: 1, offset: 5029},
			expr: &seqExpr{
				pos: position{line: 285, col: 10, offset: 5038},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 285, col: 10, offset: 5038},
						val:        "[",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 285, col: 14, offset: 5042},
						name: "_",
					},
					&zeroOrOneExpr{
						pos: position{line: 285, col: 16, offset: 5044},
						expr: &ruleRefExpr{
							pos:  position{line: 285, col: 16, offset: 5044},
							name: "Ident",
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 285, col: 23, offset: 5051},
						expr: &seqExpr{
							pos: position{line: 285, col: 24, offset: 5052},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 285, col: 24, offset: 5052},
									val:        ",",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 285, col: 28, offset: 5056},
									name: "Ident",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 285, col: 36, offset: 5064},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 285, col: 38, offset: 5066},
						val:        "]",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "Ident",
			pos:  position{line: 308, col: 1, offset: 5462},
			expr: &actionExpr{
				pos: position{line: 308, col: 9, offset: 5470},
				run: (*parser).callonIdent1,
				expr: &seqExpr{
					pos: position{line: 308, col: 9, offset: 5470},
					exprs: []interface{}{
						&charClassMatcher{
							pos:        position{line: 308, col: 9, offset: 5470},
							val:        "[a-z]i",
							ranges:     []rune{'a', 'z'},
							ignoreCase: true,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 308, col: 16, offset: 5477},
							expr: &charClassMatcher{
								pos:        position{line: 308, col: 17, offset: 5478},
								val:        "[a-z0-9]i",
								ranges:     []rune{'a', 'z', '0', '9'},
								ignoreCase: true,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 312, col: 1, offset: 5523},
			expr: &zeroOrMoreExpr{
				pos: position{line: 312, col: 5, offset: 5527},
				expr: &charClassMatcher{
					pos:        position{line: 312, col: 5, offset: 5527},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onScalarExpr1(first, rest interface{}) (interface{}, error) {
	restv := rest.([]interface{})
	if len(restv) == 0 {
		return first, nil
	}

	for i := len(restv) - 1; i > 0; i-- {
		switch v := restv[i].(type) {
		case *AddExpr:
			v.Left = restv[i-1].(Scalar)
		case *SubExpr:
			v.Left = restv[i-1].(Scalar)
		default:
			// should not happen
			return nil, fmt.Errorf("wrong type returned from AddExpr %T (%v)", v, v)
		}
	}

	switch v := restv[0].(type) {
	case *AddExpr:
		v.Left = first.(Scalar)
	case *SubExpr:
		v.Left = first.(Scalar)
	default:
		// should not happen
		return nil, fmt.Errorf("wrong type returned from AddExpr %T (%v)", v, v)
	}

	return restv[len(restv)-1], nil
}

func (p *parser) callonScalarExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScalarExpr1(stack["first"], stack["rest"])
}

func (c *current) onAddExpr1(op, arg interface{}) (interface{}, error) {
	if string(op.([]byte)) == "+" {
		return &AddExpr{
			Right: arg.(Scalar),
		}, nil
	} else {
		return &SubExpr{
			Right: arg.(Scalar),
		}, nil
	}
}

func (p *parser) callonAddExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddExpr1(stack["op"], stack["arg"])
}

func (c *current) onScalarFactor1(first, rest interface{}) (interface{}, error) {
	restv := rest.([]interface{})
	if len(restv) == 0 {
		return first, nil
	}

	for i := len(restv) - 1; i > 0; i-- {
		fmt.Println("ScalarFactor loop: ", restv[i])
		switch v := restv[i].(type) {
		case *MultExpr:
			v.Left = restv[i-1].(Scalar)
		case *DivExpr:
			v.Left = restv[i-1].(Scalar)
		default:
			// should not happen
			return nil, fmt.Errorf("wrong type returned from MultExpr %T (%v)", v, v)
		}
	}

	switch v := restv[0].(type) {
	case *MultExpr:
		v.Left = first.(Scalar)
	case *DivExpr:
		v.Left = first.(Scalar)
	default:
		// should not happen
		return nil, fmt.Errorf("wrong type returned from MultExpr %T (%v)", v, v)
	}

	return restv[len(restv)-1], nil
}

func (p *parser) callonScalarFactor1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScalarFactor1(stack["first"], stack["rest"])
}

func (c *current) onMultExpr1(op, arg interface{}) (interface{}, error) {
	if string(op.([]byte)) == "*" {
		return &MultExpr{
			Right: arg.(Scalar),
		}, nil
	} else {
		return &DivExpr{
			Right: arg.(Scalar),
		}, nil
	}
}

func (p *parser) callonMultExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultExpr1(stack["op"], stack["arg"])
}

func (c *current) onPower1(first, rest interface{}) (interface{}, error) {
	restv := rest.([]interface{})
	if len(restv) == 0 {
		return first, nil
	}

	ret := PowerExpr{
		Base: first.(Scalar),
	}
	curs := &ret

	for _, v := range restv[:len(restv)-1] {
		//fmt.Println("power rest: ", v)
		curs.Power = &PowerExpr{
			Base: v.(Scalar),
		}
		curs = curs.Power.(*PowerExpr)
	}

	curs.Power = restv[len(restv)-1].(Scalar)

	return ret, nil
}

func (p *parser) callonPower1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPower1(stack["first"], stack["rest"])
}

func (c *current) onPowerExpr1(power interface{}) (interface{}, error) {
	return power, nil
}

func (p *parser) callonPowerExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPowerExpr1(stack["power"])
}

func (c *current) onScalar2(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonScalar2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScalar2(stack["expr"])
}

func (c *current) onScalar10(ident interface{}) (interface{}, error) {
	fmt.Println("scalar var: ", string(c.text))
	return &ScalarVar{name: ident.(string)}, nil
}

func (p *parser) callonScalar10() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScalar10(stack["ident"])
}

func (c *current) onScalar13(num interface{}) (interface{}, error) {
	fmt.Println("scalar lit: ", string(c.text))
	return ScalarLit{val: num.(float64)}, nil
}

func (p *parser) callonScalar13() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScalar13(stack["num"])
}

func (c *current) onScalar16(scalar interface{}) (interface{}, error) {
	return &MultExpr{
		Left:  ScalarLit{val: -1.0},
		Right: scalar.(Scalar),
	}, nil
}

func (p *parser) callonScalar16() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScalar16(stack["scalar"])
}

func (c *current) onNumber1() (interface{}, error) {
	fmt.Println("Number: ", string(c.text))
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onAssign1(prefix, name, params interface{}) (interface{}, error) {
	ret := Func{
		Params: params.([]string),
		Name:   name.(string),
	}

	if string(prefix.([]byte)) == "def" {
		ret.IsConst = true
	}

	return ret, nil
}

func (p *parser) callonAssign1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAssign1(stack["prefix"], stack["name"], stack["params"])
}

func (c *current) onIdent1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonIdent1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdent1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
